# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: deploy site
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
        lfs: true

    - name: setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.2'
        extended: true

    - name: build site
      run: hugo --minify

    - name: ssh setup
      env:
        DEPLOY_KEY: ${{ secrets.deploy_key }}
        KNOWN_HOSTS: ${{ secrets.known_hosts }}
      run: |
        mkdir -p ~/.ssh
        echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
        echo "${DEPLOY_KEY}" >> ~/.ssh/deploy_key
        echo "IdentityFile ~/.ssh/deploy_key" >> ~/.ssh/config
        chmod -R 700 ~/.ssh

    - name: rsync site
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr -e ssh --delete
        path: public/
        remote_path: ${{ secrets.DOCUMENT_ROOT }}
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.RSYNC_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}

    - name: update algolia index
      uses: darrenjennings/algolia-docsearch-action@master
      with:
        algolia_application_id: '${{ secrets.ALGOLIA_ID }}'
        algolia_api_key: '${{ secrets.ALGOLIA_APIKEY }}'
        file: 'public/index.json'
      
